### Introduction to NumPy
It gives us mathematical function, like random

In [3]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
# Create a length 10 integer array
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Create a 3 x 5 floating point array filled with ones
# No.ones is always rows x columns
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create linear sequence starting at 0 and ending at 20 stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# Create an array of randomly distributed values between 0 and 1
np.random.random((3,3))

array([[0.33686991, 0.11724883, 0.80963064],
       [0.3000011 , 0.17269196, 0.50511291],
       [0.71559188, 0.00572615, 0.58786749]])

In [8]:
# Indexing 
np.random.seed(0)

x1 = np.random.randint(10, size=6) # One-d array
x2 = np.random.randint(10, size=(3,4)) # 2-d array
x3 = np.random.randint(10, size=(3,4,5)) # 3-d array

print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

# one dimensional indexing
print(x1)
print(x1[0], x1[3])

# multi dimensional indexing
print(x2)
print(x2[0,0])
print(x2[2,2])

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
[5 0 3 3 7 9]
5 3
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
7


In [9]:
# why do we need numpy
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [10]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.26 s ± 82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [12]:
# Astronomically faster than compute_reciprocals in 1/6th the lines
%timeit (1.0 / big_array)

4.17 ms ± 333 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
